version: '3.4'

services:
  thethinker.discordbot.workerservice:
    image: ${DOCKER_REGISTRY-}thethinkerdiscordbotworkerservice
    build:
      context: .
      dockerfile: TheThinker.DiscordBot.WorkerService/Dockerfile
    environment:
        - DiscordSettings__Token
        - DiscordSettings__Status
        - DiscordSettings__ShardManagerUri
        - LoggerConfig__ServerUri
        - LoggerConfig__ApiKey
        - DeepAIApiKey
    depends_on:
        - seq
        - TheThinker.ShardManager.WebApi

  seq:
    image: datalust/seq:2021.3.6681
    ports:
        - 8090:80
    environment:
        - ACCEPT_EULA=Y
    volumes:
        - seqdata:/data

volumes:
  seqdata:
